### ISSUE TITLE
Prerequisit dependancies Pop os 22.04

### ISSUE THREAD

**Issue by jagg2** [qzed/pbpctrl#14]
using `cargo install pbpctrl --git https://github.com/qzed/pbpctrl/`  I ran into the following prerequisite dependencies.
`sudo apt-get install libdbus-1-dev pkg-config`
`sudo apt-get install protobuf-compiler`

I'm just opening this issue to suggest adding them to the readme as Ubuntu dependencies for the cargo install

Thanks

**Comment by qzed** [comment]
Thanks! Fixed in ded40ba.
