### ISSUE TITLE
Cargo install fails

### ISSUE THREAD

**Issue by JustPassingBy06** [qzed/pbpctrl#16]
I'm a rust and cargo noob, so the problem may be caused by me, but I get the following error while installing after reinstalling my OS. I have installed successfully on this machine before, and do not know what's different now.

```
    Updating git repository `https://github.com/qzed/pbpctrl/`
error: failed to parse manifest at `/home/mathijs/.cargo/git/checkouts/pbpctrl-904862ee8bf2417c/91fda8d/libgfps/Cargo.toml`

Caused by:
  feature `edition2024` is required

  The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.80.1 (376290515 2024-07-16)).
  Consider trying a more recent nightly release.
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for more information about the status of this feature.

```

If you want any more info please let me know.

OS info: Ubuntu 24.10

**Comment by qzed** [comment]
Ah, I just recently updated the sources to the 2024 edition. You need a rust compiler that supports that, and I assume Ubuntu doesn't ship with one yet. You can either try installing rust/cargo via rustup, or install the latest tagged version (which doesn't use edition 2024 yet) via `cargo install pbpctrl --git https://github.com/qzed/pbpctrl/ --tag v0.1.7`

**Comment by JustPassingBy06** [comment]
That makes sense, thanks for the quick reply and the useful utility.
 I've installed v0.1.7 and it works as expected.
 Marking as completed!
