### ISSUE TITLE
Consider publish `Cargo.lock` for better downstream packaging work. 

### ISSUE THREAD

**Issue by VergeDX** [qzed/pbpctrl#4]
I'm packaging `pbpctrl` for `nixpkgs`(https://github.com/NixOS/nixpkgs),  
which need `Cargo.lock` file for deterministic build, otherwise we can only store lock in our repo.  
I think publish lock file as author is a better choice : )

**Comment by qzed** [comment]
I've added the `Cargo.lock` file.
