### ISSUE TITLE
Option for cycling through anc options

### ISSUE THREAD

**Issue by Raqbit** [qzed/pbpctrl#5]
It would be nice if `pbpctrl set anc` could have an option that allows you to cycle through ANC modes instead of only allowing you to set it. This would make it easy to create a keyboard shortcut to cycle through the ANC modes, following the order configured on the device.

**Comment by qzed** [comment]
Implemented in 05a2f8886f33da9b3282e135356488659c0c992b.

A note: The order is fixed and can't be changed as far as I know. I believe it's only possible to enable/disable certain states in the ANC cycle. `pbpctrl set anc cycle-next` / `pbpctrl set anc cycle-prev` can now be used similar to how the ANC gesture works, following the (fixed) cycle in the app, skipping disabled states.
